services:
  api:
    build:
      context: .
      dockerfile: Tournament.API/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"

  migrations:
    build:
      context: .
      dockerfile: Tournament.Infrastructure/Dockerfile.migrations
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tournament
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
