services:
  api:
   environment:
   - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tournament;Username=postgres;Password=postgres
   build:
      context: .
      dockerfile: Tournament.API/Dockerfile
   depends_on:
      - db
   ports:
      - "8080:8080"

  migrations:
   environment:
    - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tournament;Username=postgres;Password=postgres
   build:
      context: .
      dockerfile: Tournament.Infrastructure/Dockerfile.migrations
   depends_on:
      - db
  db:
    image: postgres:16
    container_name: cardhub-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tournament
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
